import pytest

from part2sec15exercisestep4.helpers import approximate_pattern_matching

@pytest.mark.parametrize('p, t, d, o', (('ATTCTGGA','CGCCCGAATCCAGAACGCATTCCCATATTTCGGGACCACTGGCCTCCACGGTACGGACGTCAATCAAAT', 3, '6 7 26 27'),
                                        ('AAA', 'TTTTTTAAATTTTAAATTTTTT', 2, '4 5 6 7 8 11 12 13 14 15'),
                                        ('GAGCGCTGG', 'GAGCGCTGGGTTAACTCGCTACTTCCCGACGAGCGCTGTGGCGCAAATTGGCGATGAAACTGCAGAGAGAACTGGTCATCCAACTGAATTCTCCCCGCTATCGCATTTTGATGCGCGCCGCGTCGATT', 2, '0 30 66'),
                                        ('AATCCTTTCA', 'CCAAATCCCCTCATGGCATGCATTCCCGCAGTATTTAATCCTTTCATTCTGCATATAAGTAGTGAAGGTATAGAAACCCGTTCAAGCCCGCAGCGGTAAAACCGAGAACCATGATGAATGCACGGCGATTGCGCCATAATCCAAACA', 3, '3 36 74 137'),
                                        ('CCGTCATCC', 'CCGTCATCCGTCATCCTCGCCACGTTGGCATGCATTCCGTCATCCCGTCAGGCATACTTCTGCATATAAGTACAAACATCCGTCATGTCAAAGGGAGCCCGCAGCGGTAAAACCGAGAACCATGATGAATGCACGGCGATTGC', 3, '0 7 36 44 48 72 79 112'),
                                        ('TTT', 'AAAAAA', 3, '0 1 2 3'),
                                        ('CCA', 'CCACCT', 0, '0'),
                                        ('GTGCCG', 'AGCGTGCCGAAATATGCCGCCAGACCTGCTGCGGTGGCCTCGCCGACTTCACGGATGCCAAGTGCATAGAGGAAGCGAGCAAAGGTGGTTTCTTTCGCTTTATCCAGCGCGTTAACCACGTTCTGTGCCGACTTT', 3, '3 13 16 22 25 27 28 30 33 34 36 39 47 54 61 71 76 84 87 91 101 106 119 124')))
def test_approximate_pattern_matching(p, t, d, o):
    a = approximate_pattern_matching(p, t, d)
    assert ' '.join(a) == o
