import pytest

from part2sec15exercisestep3.helpers import hamming_distance

@pytest.mark.parametrize('p,q,v', (('GGGCCGTTGGT', 'GGACCGTTGAC', 3),
                                   ('AAAA', 'TTTT', 4),
                                   ('ACGTACGT', 'TACGTACG', 8),
                                   ('ACGTACGT', 'CCCCCCCC', 6),
                                   ('ACGTACGT', 'TGCATGCA', 8),
                                   ('GATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACT', 'AATAGCAGCTTCTCAACTGGTTACCTCGTATGAGTAAATTAGGTCATTATTGACTCAGGTCACTAACGTCT', 15),
                                   ('AGAAACAGACCGCTATGTTCAACGATTTGTTTTATCTCGTCACCGGGATATTGCGGCCACTCATCGGTCAGTTGATTACGCAGGGCGTAAATCGCCAGAATCAGGCTG', 'AGAAACCCACCGCTAAAAACAACGATTTGCGTAGTCAGGTCACCGGGATATTGCGGCCACTAAGGCCTTGGATGATTACGCAGAACGTATTGACCCAGAATCAGGCTC', 28),
                                   ('AGCGTGCCGAAATATGCCGCCAGACCTGCTGCGGTGGCCTCGCCGACTTCACGGATGCCAAGTGCATAGAGGAAGCGAGCAAAGGTGGTTTCTTTCGCTTTATCCAGCGCGTTAACCACGTTCTGTGCCGACTTT', 'AGAAACAGACCGCTATGTTCAACGATTTGTTTTATCTCGTCACCGGGATATTGCGGCCACTCATCGGTCAGTTGATTACGCAGGGCGTAAATCGCCAGAATCAGGCTGAAACCCTACGGACAGGTTTACGAACCT', 103)))
def test_distance(p,q,v):
    assert hamming_distance(p,q) == v
